IF NOT EXISTS (
    select * from sysobjects where name='MangaListFromExcel' and xtype='U'
) CREATE TABLE MangaListFromExcel (
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [Title] NVARCHAR(73),
    [Read chapters] INT,
    [Score] INT,
    [Read volumes] INT,
    [Volumes] INT,
    [Genres] NVARCHAR(20),
    [Chapters] INT,
    [Type] NVARCHAR(8),
    [My status] NVARCHAR(15),
	[Additional information] NVARCHAR(20)
);
INSERT INTO MangaListFromExcel VALUES
    (N'Adabana',NULL,NULL,NULL,NULL,NULL,1,N'One Shot',NULL,NULL),
    (N'Asahina Koharu no Mousou Biyori',NULL,NULL,NULL,NULL,NULL,1,N'One Shot',NULL,NULL),
    (N'Door to Heaven',NULL,NULL,NULL,NULL,NULL,1,N'One Shot',NULL,NULL),
	(N'Okaa-san',NULL,NULL,NULL,NULL,NULL,1,N'One Shot',NULL,NULL),
    (N'Terror',NULL,NULL,NULL,NULL,NULL,1,N'One Shot',NULL,NULL),
    (N'Rec: Kimi ga Naita Hi',NULL,NULL,NULL,NULL,NULL,4,N'Manga',NULL,NULL),
    (N'Waga Tousou (Manga)',NULL,NULL,NULL,NULL,NULL,4,N'Manga',NULL,NULL),
    (N'Mimi no Kaidan',NULL,NULL,NULL,NULL,NULL,6,N'Manga',NULL,NULL),
    (N'Kurokami no Helga',NULL,NULL,NULL,NULL,NULL,7,N'Manga',NULL,NULL),
    (N'Manga of the Dead',NULL,NULL,NULL,NULL,NULL,8,N'Manga',NULL,NULL),
    (N'Watashitachi no Shiawase na Jikan',NULL,NULL,NULL,NULL,NULL,8,N'Manga',NULL,NULL),
    (N'Akuma to Dolce',NULL,NULL,NULL,NULL,NULL,9,N'Manga',NULL,NULL),
    (N'Blade of the Immortal',NULL,NULL,NULL,NULL,NULL,9,N'Manga',NULL,NULL),
    (N'Tokyo Zombie',NULL,NULL,NULL,NULL,NULL,9,N'Manga',NULL,NULL),
    (N'Alive',NULL,NULL,NULL,NULL,NULL,10,N'Manga',NULL,NULL),
    (N'Mashounen BT',NULL,NULL,NULL,NULL,NULL,11,N'Manga',NULL,NULL),
    (N'Cry Eye',NULL,NULL,NULL,NULL,NULL,12,N'Manga',NULL,NULL),
    (N'Suiiki',NULL,NULL,NULL,NULL,NULL,12,N'Manga',NULL,NULL),
    (N'Abara',NULL,NULL,NULL,NULL,NULL,13,N'Manga',NULL,NULL),
    (N'Satougashi no Dangan wa Uchinukenai: A Lollypop or A Bullet',NULL,NULL,NULL,NULL,NULL,13,N'Manga',NULL,NULL),
    (N'Kiss de Seiyaku',NULL,NULL,NULL,NULL,NULL,14,N'Manga',NULL,NULL),
    (N'Koudelka',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Life is Money',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Nijigahara Holograph',NULL,NULL,NULL,NULL,NULL,15,N'Manga',NULL,NULL),
    (N'Tokyo Girls Destruction',NULL,NULL,NULL,NULL,NULL,15,N'Manga',NULL,NULL),
    (N'Mousugu Shinu Hito',NULL,NULL,NULL,NULL,NULL,16,N'Manga',NULL,NULL),
    (N'Ningyo Series',NULL,NULL,NULL,NULL,NULL,16,N'Manga',N'adaptacja',NULL),
    (N'RealPG',NULL,NULL,NULL,NULL,NULL,16,N'Manga',NULL,NULL),
    (N'H・E: The Hunt for Energy',NULL,NULL,NULL,NULL,NULL,17,N'Manga',NULL,NULL),
    (N'6 no Trigger',NULL,NULL,NULL,NULL,NULL,20,N'Manga',NULL,NULL),
    (N'Blaster Knuckle',NULL,NULL,NULL,NULL,NULL,20,N'Manga',NULL,NULL),
    (N'Naisho no Mangaka Tonari no Yutori-san',NULL,NULL,NULL,NULL,NULL,20,N'Manga',NULL,NULL),
    (N'Kasou Ryouiki no Elysion',NULL,NULL,NULL,NULL,NULL,21,N'Novel',NULL,NULL),
    (N'Misumisou',NULL,NULL,NULL,NULL,NULL,21,N'Manga',NULL,NULL),
    (N'Monochrome Myst',NULL,NULL,NULL,NULL,NULL,21,N'Manga',NULL,NULL),
    (N'Kiben Gakuha, Yotsuya-senpai no Kaidan.',NULL,NULL,NULL,NULL,NULL,22,N'Manga',NULL,NULL),
    (N'Akarui Sekai Keikaku',NULL,NULL,NULL,NULL,NULL,23,N'Manga',NULL,NULL),
    (N'Limit',NULL,NULL,NULL,NULL,NULL,23,N'Manga',NULL,NULL),
    (N'Crimezone',NULL,NULL,NULL,NULL,NULL,24,N'Manga',NULL,NULL),
    (N'Gakkyuu Houtei',NULL,NULL,NULL,NULL,NULL,24,N'Manga',NULL,NULL),
    (N'Mizu ni Sumu Hana',NULL,NULL,NULL,NULL,NULL,24,N'Manga',NULL,NULL),
    (N'Planetes',NULL,NULL,NULL,NULL,NULL,27,N'Manga',NULL,NULL),
    (N'"Fushigi" Toriatsukaimasu: Tsukumodou Kottouten',NULL,NULL,NULL,NULL,NULL,28,N'Novel',NULL,NULL),
    (N'Full House Kiss',NULL,NULL,NULL,NULL,NULL,28,N'Manga',NULL,NULL),
    (N'Medaka Box',NULL,NULL,NULL,NULL,NULL,28,N'Manga',NULL,NULL),
    (N'Kuang Shen',NULL,NULL,NULL,NULL,NULL,29,N'Manhua',NULL,NULL),
    (N'Zombiepowder.',NULL,NULL,NULL,NULL,NULL,30,N'Manga',NULL,NULL),
    (N'The World''s Greatest Little Sister',NULL,NULL,NULL,NULL,NULL,36,N'Novel',NULL,NULL),
    (N'Nickelodeon',NULL,NULL,NULL,NULL,NULL,39,N'Manga',NULL,NULL),
    (N'Kyuukyoku Venus',NULL,NULL,NULL,NULL,NULL,43,N'Manga',NULL,NULL),
    (N'Kurogane',NULL,NULL,NULL,NULL,NULL,45,N'Manga',NULL,NULL),
    (N'Red Raven',NULL,NULL,NULL,NULL,NULL,45,N'Manga',NULL,NULL),
    (N'Yuusha, Aruiwa Bakemono to Yobareta Shoujo',NULL,NULL,NULL,NULL,NULL,46,N'Novel',NULL,NULL),
    (N'Hitsuji no Uta',NULL,NULL,NULL,NULL,NULL,47,N'Manga',N'adaptacja',NULL),
    (N'Inu x Boku SS',NULL,NULL,NULL,NULL,NULL,49,N'Manga',NULL,NULL),
    (N'Doubt',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Saver',NULL,NULL,NULL,NULL,NULL,55,N'Manhwa',NULL,NULL),
    (N'ənígmə',NULL,NULL,NULL,NULL,NULL,56,N'Manga',NULL,NULL),
    (N'Sensen Spike Hills',NULL,NULL,NULL,NULL,NULL,57,N'Manga',NULL,NULL),
    (N'Kaze no Tani no Nausicaä',NULL,NULL,NULL,NULL,NULL,59,N'Manga',NULL,NULL),
    (N'Koe no Katachi',NULL,NULL,NULL,NULL,NULL,64,N'Manga',NULL,NULL),
    (N'Orange Yane no Chiisana Ie',NULL,NULL,NULL,NULL,NULL,64,N'Manga',NULL,NULL),
    (N'Aria',NULL,NULL,NULL,NULL,NULL,67,N'Manga',NULL,NULL),
    (N'Yuureitou',NULL,NULL,NULL,NULL,NULL,80,N'Manga',NULL,NULL),
    (N'Freesia',NULL,NULL,NULL,NULL,NULL,82,N'Manga',NULL,NULL),
    (N'ES - Eternal Sabbath',NULL,NULL,NULL,NULL,NULL,83,N'Manga',NULL,NULL),
    (N'Black Bird',NULL,NULL,NULL,NULL,NULL,84,N'Manga',NULL,NULL),
    (N'Angel Densetsu',NULL,NULL,NULL,NULL,NULL,89,N'Manga',N'adaptacja',NULL),
    (N'Mx0',NULL,NULL,NULL,NULL,NULL,99,N'Manga',NULL,NULL),
    (N'Basara',NULL,NULL,NULL,NULL,NULL,107,N'Manga',NULL,NULL),
    (N'Koroshiya 1',NULL,NULL,NULL,NULL,NULL,114,N'Manga',NULL,NULL),
    (N'Karin',NULL,NULL,NULL,NULL,NULL,128,N'Manga',N'adaptacja',NULL),
    (N'City of Darkness',NULL,NULL,NULL,NULL,NULL,136,N'Manhua',N'więcej?',NULL),
    (N'Oyasumi Punpun',NULL,NULL,NULL,NULL,NULL,147,N'Manga',NULL,NULL),
    (N'Lord',NULL,NULL,NULL,NULL,NULL,154,N'Manga',NULL,NULL),
    (N'Akumetsu',NULL,NULL,NULL,NULL,NULL,162,N'Manga',NULL,NULL),
    (N'Homunculus',NULL,NULL,NULL,NULL,NULL,166,N'Manga',NULL,NULL),
    (N'Gamble Fish',NULL,NULL,NULL,NULL,NULL,167,N'Manga',NULL,NULL),
    (N'Kokou no Hito',NULL,NULL,NULL,NULL,NULL,170,N'Manga',NULL,NULL),
    (N'Feng Shen Ji',NULL,NULL,NULL,NULL,NULL,182,N'Manhua',NULL,NULL),
    (N'Eden no Ori',NULL,NULL,NULL,NULL,NULL,185,N'Manga',NULL,NULL),
    (N'Fuan no Tane',NULL,NULL,NULL,NULL,NULL,188,N'Manga',NULL,NULL),
    (N'Gamaran',NULL,NULL,NULL,NULL,NULL,194,N'Manga',NULL,NULL),
    (N'Bloody Monday',NULL,NULL,NULL,NULL,NULL,200,N'Manga',N'czytane',NULL),
    (N'20th Century Boys',NULL,NULL,NULL,NULL,NULL,273,N'Manga',NULL,NULL),
    (N'Slam Dunk',NULL,NULL,NULL,NULL,NULL,276,N'Manga',N'adaptacja',NULL),
    (N'Hareluya II Boy',NULL,NULL,NULL,NULL,NULL,305,N'Manga',NULL,NULL),
    (N'Samurai Deeper Kyo',NULL,NULL,NULL,NULL,NULL,307,N'Manga',NULL,NULL),
    (N'Higanjima',NULL,NULL,NULL,NULL,NULL,330,N'Manga',NULL,NULL),
    (N'Hotel',NULL,NULL,NULL,NULL,NULL,331,N'Manga',NULL,NULL),
    (N'Shamo',NULL,NULL,NULL,NULL,NULL,338,N'Manga',NULL,NULL),
    (N'Ushio to Tora',NULL,NULL,NULL,NULL,NULL,349,N'Manga',N'adaptacja',NULL),
    (N'Ad Astra: Scipio to Hannibal',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Apocalypse no Toride',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Banya: The Explosive Delivery Man',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Blackout',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Dorohedoro',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Goth',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Hinamatsuri',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Honorable Baek Dong Soo',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Kakegurui',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Midnight Secretary',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Need a Girl',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Ore to Akuma no Blues',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Overlord',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Piano no Mori',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Shin Angyo Onshi',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Shinobi Life',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Tate no Yuusha no Nariagari',NULL,NULL,NULL,NULL,NULL,NULL,N'Novel',NULL,NULL),
    (N'The Breaker',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'The Ring',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Tokage no Ou',NULL,NULL,NULL,NULL,NULL,NULL,N'Novel',N'15 mangi',NULL),
    (N'Tomodachi Game',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Trinity Seven: 7-nin no Masho Tsukai',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Übel Blatt',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Uzumaki',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Vinland Saga',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Yurusarete Inai Watashitachi',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Zero no Shiniki',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Aku no Higan',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Ana Satsujin',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Azumi',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',N'dużo',NULL),
    (N'Billy Bat',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Black Museum Springald',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Cyber Blue',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Gekiryuuchi',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Hell Blade',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Holyland',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Horimiya',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Houkago Hokenshitsu',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Jinrou Game',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Kanojo wa Mada Koi wo Shiranai',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Karakai Jouzu no Takagi-san',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Kiseijuu',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Kono Shima ni wa Midara de Jaaku na Mono ga Sumu',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Kyuusen no Shima',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'L♥DK',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Liar Game',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Mushoku Tensei: Isekai Ittara Honki Dasu',NULL,NULL,NULL,NULL,NULL,NULL,N'Novel',NULL,NULL),
    (N'Namaikizakari.',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Orange Marmalade',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Pluto',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Psychometrer Eiji',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Real',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Rokka no Yuusha',NULL,NULL,NULL,NULL,NULL,NULL,N'Novel',NULL,NULL),
    (N'Shindere Shoujo to Kodoku na Shinigami',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Shinigami-sama ni Saigo no Onegai wo',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Shounen Shoujo Hyouryuuki',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Soul Catcher(S)',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Sun-ken Rock',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Kouishou Radio',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'The New Gate',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'3-gatsu no Lion',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',N'adaptacja',NULL),
    (N'7Seeds',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Abide in the Wind',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Afterschool War Activities',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Ajin',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Akagami no Shirayuki-hime',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Aku no Meshitsukai',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Annarasumanara',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Anne Freaks',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Arachnid',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Area D: Inou Ryouiki',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Baccano! 1931 The Grand Punk Railroad',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Battle Royale',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Blood and Steel',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhua',NULL,NULL),
    (N'Boku wa Mari no Naka',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Boukyaku no Haou Rolan',NULL,NULL,NULL,NULL,NULL,NULL,N'Novel',NULL,NULL),
    (N'Bravely Default: Flying Fairy',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Bungou Stray Dogs',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',N'adaptacja',NULL),
    (N'Bus Gamer - Pilot Edition',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Conductor',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Corpse Party: Musume',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Crepuscule',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Darwin`s game',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Dimension W',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',N'adaptacja',NULL),
    (N'Douluo Dalu',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhua',NULL,NULL),
    (N'Dr. Frost',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Embalming: The Another Tale of Frankenstein',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Hai to Gensou no Grimgar',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Helter Skelter',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Hito Hitori Futari',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Hito Kui',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'I Am a Hero',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Ibitsu',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Id',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Ikigami',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Imawa no Kuni no Alice',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Iris Zero',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Kamisama Hajimemashita',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Kamisama no Iutoori',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Keyman: The Hand of Judgement',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Kimi no Knife',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Kuusen Madoushi Kouhosei no Kyoukan',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Last Game',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Litchi☆Hikari Club',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Ma no Kakera',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Mahou Shoujo of the End',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Maoyuu Maou Yuusha: ''Kono Watashi no Mono to Nare, Yuusha yo'' ''Kotowaru!''',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',N'dużo',NULL),
    (N'Marginal Operation',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Masamune-kun no Revenge',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Mushoku Tensei: Isekai Ittara Honki Dasu',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Nabi',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Nurarihyon no Mago',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',N'adaptacja',NULL),
    (N'Otome Youkai Zakuro',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',N'adaptacja',NULL),
    (N'Oukoku game',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Ousama Game',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',N'<---',NULL),
    (N'Papillon: Hana to Chou',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Ping',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Priest',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Psycome',NULL,NULL,NULL,NULL,NULL,NULL,N'Novel',NULL,NULL),
    (N'QP',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Re:Monster',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Re:Monster',NULL,NULL,NULL,NULL,NULL,NULL,N'Novel',NULL,NULL),
    (N'Real Account',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'ReLIFE',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',N'adaptacja',NULL),
    (N'Rin',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Ruler of the Land',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Saiteihen no Otoko',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Seitokai Tantei Kirika',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Sengoku Youko',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Shinazu no Ryouken',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Shuuen no Shiori',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Supernatural Investigation Department',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL),
    (N'Tate no Yuusha no Nariagari',NULL,NULL,NULL,NULL,NULL,NULL,N'Novel',NULL,NULL),
    (N'Tensei shitara Slime Datta Ken',NULL,NULL,NULL,NULL,NULL,NULL,N'Novel',NULL,NULL),
    (N'Toaru Kagaku no Railgun',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',N'dużo',NULL),
    (N'Tsukihime',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Utsuro no Hako to Zero no Maria',NULL,NULL,NULL,NULL,NULL,NULL,N'Novel',NULL,NULL),
    (N'Vagabond',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Variante',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Watashi no Ookami-kun',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'World Customize Creator',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Yami no Koe',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Yaotsukumo',NULL,NULL,NULL,NULL,NULL,NULL,N'Manga',NULL,NULL),
    (N'Zippy Ziggy',NULL,NULL,NULL,NULL,NULL,NULL,N'Manhwa',NULL,NULL);
SELECT * FROM dbo.MangaListFromExcel;