//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAL_Excel_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimeListFromMAL
    {
        public int ID { get; set; }
        public Nullable<int> myanimelist { get; set; }
        public Nullable<int> myanimelist_myinfo { get; set; }
        public Nullable<int> myanimelist_myinfo_user_id { get; set; }
        public string myanimelist_myinfo_user_name { get; set; }
        public Nullable<int> myanimelist_myinfo_user_export_type { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_anime { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_watching { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_completed { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_onhold { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_dropped { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_plantowatch { get; set; }
        public Nullable<int> myanimelist_anime { get; set; }
        public Nullable<int> myanimelist_anime_series_animedb_id { get; set; }
        public string myanimelist_anime_series_title { get; set; }
        public string myanimelist_anime_series_type { get; set; }
        public Nullable<int> myanimelist_anime_series_episodes { get; set; }
        public Nullable<int> myanimelist_anime_my_id { get; set; }
        public Nullable<int> myanimelist_anime_my_watched_episodes { get; set; }
        public string myanimelist_anime_my_start_date { get; set; }
        public string myanimelist_anime_my_finish_date { get; set; }
        public Nullable<int> myanimelist_anime_my_rated { get; set; }
        public Nullable<int> myanimelist_anime_my_score { get; set; }
        public Nullable<int> myanimelist_anime_my_dvd { get; set; }
        public Nullable<int> myanimelist_anime_my_storage { get; set; }
        public string myanimelist_anime_my_status { get; set; }
        public Nullable<int> myanimelist_anime_my_comments { get; set; }
        public Nullable<int> myanimelist_anime_my_times_watched { get; set; }
        public Nullable<int> myanimelist_anime_my_rewatch_value { get; set; }
        public Nullable<int> myanimelist_anime_my_tags { get; set; }
        public Nullable<int> myanimelist_anime_my_rewatching { get; set; }
        public Nullable<int> myanimelist_anime_my_rewatching_ep { get; set; }
        public Nullable<int> myanimelist_anime_update_on_import { get; set; }
    }
}
