//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAL_Excel_App
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class AnimeListFromExcel
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Genres { get; set; }
        public Nullable<int> Watched_episodes { get; set; }
        public Nullable<int> Score { get; set; }
        public string Additional_information { get; set; }
        public Nullable<int> Episodes { get; set; }
        public string Type { get; set; }
        public string My_status { get; set; }
    }
}
