//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAL_Excel_App
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MangaListFromMAL
    {
        public int ID { get; set; }
        public Nullable<int> myanimelist { get; set; }
        public Nullable<int> myanimelist_myinfo { get; set; }
        public Nullable<int> myanimelist_myinfo_user_id { get; set; }
        public string myanimelist_myinfo_user_name { get; set; }
        public Nullable<int> myanimelist_myinfo_user_export_type { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_manga { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_reading { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_completed { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_onhold { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_dropped { get; set; }
        public Nullable<int> myanimelist_myinfo_user_total_plantoread { get; set; }
        public Nullable<int> myanimelist_manga { get; set; }
        public Nullable<int> myanimelist_manga_manga_mangadb_id { get; set; }
        public string myanimelist_manga_manga_title { get; set; }
        public Nullable<int> myanimelist_manga_manga_volumes { get; set; }
        public Nullable<int> myanimelist_manga_manga_chapters { get; set; }
        public Nullable<int> myanimelist_manga_my_id { get; set; }
        public Nullable<int> myanimelist_manga_my_read_volumes { get; set; }
        public Nullable<int> myanimelist_manga_my_read_chapters { get; set; }
        public string myanimelist_manga_my_start_date { get; set; }
        public string myanimelist_manga_my_finish_date { get; set; }
        public Nullable<int> myanimelist_manga_my_scanalation_group { get; set; }
        public Nullable<int> myanimelist_manga_my_score { get; set; }
        public Nullable<int> myanimelist_manga_my_storage { get; set; }
        public string myanimelist_manga_my_status { get; set; }
        public Nullable<int> myanimelist_manga_my_comments { get; set; }
        public Nullable<int> myanimelist_manga_my_times_read { get; set; }
        public Nullable<int> myanimelist_manga_my_tags { get; set; }
        public Nullable<int> myanimelist_manga_my_reread_value { get; set; }
        public Nullable<int> myanimelist_manga_update_on_import { get; set; }
    }
}
